[package]
name = "ipns-plugin-interface"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
extism = "0.4.0"
serde_json = "1.0"
anyhow = "1.0.69"
